# Generated by Django 5.0.2 on 2024-02-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="thumbnail",
            field=models.ImageField(
                default="https://via.placeholder.com/200", upload_to="thumbnails"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movie",
            field=models.FileField(upload_to="movies"),
        ),
    ]
