# Generated by Django 5.0.2 on 2024-02-11 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_movie_thumbnail_alter_movie_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="watch_count",
        ),
    ]
