# Generated by Django 5.0.2 on 2024-02-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_remove_movie_watch_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="ranking",
            field=models.FloatField(default=1),
        ),
    ]
